### ISSUE TITLE
asl_gui asks to migrate to PyPI

### ISSUE THREAD

**Issue by t1tan1k** [ibme-qubic/oxford_asl#13]
Good day! I am trying to run asl_gui after clear installation of FSL on Ubuntu and in CentOS virtual machine. In both cases typing asl_gui in terminal leads to this code:

/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/wx/lib/pubsub/__init__.py:25: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  wx.wxPyDeprecationWarning)
02:06:15 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
Traceback (most recent call last):
  File "/usr/local/fsl/bin/asl_gui", line 14, in <module>
    main.main()
  File "/usr/local/fsl/python/oxford_asl/gui/main.py", line 166, in main
    top = AslGui()
  File "/usr/local/fsl/python/oxford_asl/gui/main.py", line 64, in __init__
    preview = PreviewPanel(hpanel)
  File "/usr/local/fsl/python/oxford_asl/gui/preview_fsleyes.py", line 108, in __init__
    self.overlayList, masterDisplayCtx, self._fsleyes_frame = fsleyes_embed(None, make_fsleyesframe=False)
  File "/usr/local/fsl/python/oxford_asl/gui/preview_fsleyes.py", line 84, in fsleyes_embed
    fslgl.getGLContext(parent=parent, ready=ready)
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 458, in getGLContext
    thismod._glContext = GLContext(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'parent'

Is there any solution?
Thank you in advance.

**Comment by ribal-aladeeb** [comment]
I get a very similar error. This is the output:

```
/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/wx/lib/pubsub/__init__.py:25: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  wx.wxPyDeprecationWarning)
Gtk-Message: 16:59:02.232: Failed to load module "overlay-scrollbar"
Gtk-Message: 16:59:02.233: Failed to load module "atk-bridge"
Gtk-Message: 16:59:02.233: Failed to load module "unity-gtk-module"
Gtk-Message: 16:59:02.235: Failed to load module "canberra-gtk-module"
04:59:02 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
Traceback (most recent call last):
  File "/usr/local/fsl/bin/asl_gui", line 14, in <module>
    main.main()
  File "/usr/local/fsl/python/oxford_asl/gui/main.py", line 166, in main
    top = AslGui()
  File "/usr/local/fsl/python/oxford_asl/gui/main.py", line 64, in __init__
    preview = PreviewPanel(hpanel)
  File "/usr/local/fsl/python/oxford_asl/gui/preview_fsleyes.py", line 108, in __init__
    self.overlayList, masterDisplayCtx, self._fsleyes_frame = fsleyes_embed(None, make_fsleyesframe=False)
  File "/usr/local/fsl/python/oxford_asl/gui/preview_fsleyes.py", line 84, in fsleyes_embed
    fslgl.getGLContext(parent=parent, ready=ready)
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 458, in getGLContext
    thismod._glContext = GLContext(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'parent'
```

I opened the asl_gui script and found that it tries to get the value of env variable $FSLDEVDIR which is not set in my current installation. I tried setting it to the same value as $FSLDIR in my .zshrc but I get the same error.

**Comment by ribal-aladeeb** [comment]
Update: @t1tan1k I read the  `/usr/local/fsl/python/oxford_asl/gui/main.py` file which specifies that you can run `asl_gui` with a `--matplotlib` argument (I think this means it uses matplotlib instead of fsleyes for plotting your images) and it worked without throwing the `TypeError: __init__() got an unexpected keyword argument 'parent'` that we both got. Hope this helps
