### ISSUE TITLE
asl_gui errors

### ISSUE THREAD

**Issue by khealey1** [ibme-qubic/oxford_asl#5]
I've downloaded and replaced the package files within a pathed directory, yet I'm still getting the following errors when trying to call up the asl_gui:

Traceback (most recent call last):
  File "/usr/local/fsl/bin/asl_gui", line 12, in <module>
    from asl.gui import main
  File "/usr/local/fsl/bin/python/asl/gui/__init__.py", line 25, in <module>
    from .analysis_tab import AslAnalysis
  File "/usr/local/fsl/bin/python/asl/gui/analysis_tab.py", line 4, in <module>
    from .widgets import TabPage
  File "/usr/local/fsl/bin/python/asl/gui/widgets.py", line 10, in <module>
    from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
ImportError: No module named backend_wxagg

Does anyone have any input/suggestions?

**Comment by mcraig-ibme** [comment]
Hi, apologies for the lack of response, I have not been getting GitHub notifications and a number of issues have been raised here without me realising.

If this issue is still occurring in current code (FSL 6.0.1 or later) please let me know. From the above it looks like an issue with the matplotlib installation.

**Comment by mcraig-ibme** [comment]
Closing historical issue
